paths:
  data_dir: data
  combined_csv: data/combined.csv
  preference_csv: data/preference.csv
model:
  gat_hidden_dim: 16
  gat_heads: 2
  gat_epochs: 100
  gat_lr: 0.01
hours_per_fortnight: 80
preference_weight: 2.0