paths:
  combined_csv: "data/combined.csv"
  output_features_csv: "../data/edges_for_gat_features.csv"

model:
  gat_hidden_dim: 8      # GATConv hidden channels
  gat_heads: 2           # Number of attention heads
  gat_epochs: 100        # Number of training epochs
  gat_lr: 0.01           # Learning rate

split:
  test_weeks: 2          # Number of weeks to hold out for test set